import { useState } from 'react';
import { Plus, Trash2, X } from 'lucide-react';

function localDateTimeNow() { const now = new Date(); now.setMinutes(now.getMinutes() - now.getTimezoneOffset()); return now.toISOString().slice(0, 16); }
const blankEntry = (side = null) => ({ id: globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random()}`, weight: '', assistanceWeight: '', reps: '', sets: '', side });
const initialEntry = () => ({ exercise: '', entries: [blankEntry()], recordedAt: localDateTimeNow(), sideMode: false, sidesSame: true, assisted: false, memo: '' });

function EntryRows({ title, side, items, assisted, onUpdate, onAdd, onDelete }) {
  return <div className="entry-group">{title && <p className="side-heading">{title}</p>}<div className="entry-headings"><span aria-hidden="true" /><span>{assisted ? '補助重量' : '重量'}</span><span>回数</span><span>セット数</span><span aria-hidden="true" /></div><div className="set-inputs">{items.map((item, index) => <div className="set-input-row entry-input-row" key={item.id}><span className="set-label">{index + 1}</span><label className="field"><span className="sr-only">{assisted ? '補助重量' : '重量'}</span><span className="input-with-unit"><input required min="0" step="0.5" inputMode="decimal" type="number" placeholder="0" value={assisted ? item.assistanceWeight : item.weight} onChange={(e) => onUpdate(item.id, assisted ? 'assistanceWeight' : 'weight', e.target.value)} /><span>kg</span></span></label><label className="field"><span className="sr-only">回数</span><span className="input-with-unit"><input required min="1" step="1" inputMode="numeric" type="number" placeholder="0" value={item.reps} onChange={(e) => onUpdate(item.id, 'reps', e.target.value)} /><span>回</span></span></label><label className="field"><span className="sr-only">セット数</span><span className="input-with-unit"><input required min="1" step="1" inputMode="numeric" type="number" placeholder="0" value={item.sets} onChange={(e) => onUpdate(item.id, 'sets', e.target.value)} /><span>set</span></span></label>{items.length > 1 && <button className="icon-button delete-meal set-delete" type="button" onClick={() => onDelete(item.id)} aria-label={`入力行${index + 1}を削除`}><Trash2 size={16} /></button>}</div>)}</div><button className="add-set-button" type="button" onClick={() => onAdd(side)}><Plus size={16} />重量・回数・セットを追加</button></div>;
}

export default function TrainingEntry({ onAdd, onCancel }) {
  const [entry, setEntry] = useState(initialEntry);
  const entriesFor = (side) => entry.entries.filter((item) => item.side === side);
  const totalSets = entry.entries.reduce((sum, item) => sum + Number(item.sets || 0), 0);
  const volume = entry.entries.reduce((sum, item) => sum + Number(entry.assisted ? item.assistanceWeight || 0 : item.weight || 0) * Number(item.reps || 0) * Number(item.sets || 0), 0);
  function updateEntry(id, key, value) { setEntry((current) => ({ ...current, entries: current.entries.map((item) => item.id === id ? { ...item, [key]: value } : item) })); }
  function addRow(side) { setEntry((current) => ({ ...current, entries: [...current.entries, blankEntry(side)] })); }
  function deleteRow(id) { setEntry((current) => ({ ...current, entries: current.entries.filter((item) => item.id !== id) })); }
  function setSideMode(enabled) { setEntry((current) => ({ ...current, sideMode: enabled, sidesSame: true, entries: current.entries.map((item) => ({ ...item, side: enabled ? 'both' : null })) })); }
  function setSidesSame(same) { setEntry((current) => { const common = current.entries.filter((item) => item.side === 'both' || item.side === null); const base = common.length ? common : current.entries.filter((item) => item.side === 'right'); return { ...current, sidesSame: same, entries: same ? base.map((item) => ({ ...item, side: 'both' })) : [...base.map((item) => ({ ...item, side: 'right' })), ...base.map((item) => ({ ...item, id: `${item.id}-left-${Date.now()}`, side: 'left' }))] }; }); }
  function submit(event) { event.preventDefault(); onAdd({ id: globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random()}`, exercise: entry.exercise.trim(), sideMode: entry.sideMode, assisted: entry.assisted, memo: entry.memo.trim(), entries: entry.entries.map((item) => ({ weight: entry.assisted ? undefined : Number(item.weight), assistanceWeight: entry.assisted ? Number(item.assistanceWeight) : undefined, reps: Number(item.reps), sets: Number(item.sets), side: item.side })), recordedAt: new Date(entry.recordedAt).toISOString(), createdAt: new Date().toISOString() }); }
  const commonSide = entry.sideMode ? 'both' : null;
  return <form className="meal-form training-form" onSubmit={submit}><div className="form-panel-heading"><div><p className="eyebrow">NEW TRAINING LOG</p><h3>トレーニングを記録</h3></div><button className="icon-button close-form" type="button" onClick={onCancel} aria-label="入力を閉じる"><X size={19} /></button></div><label className="field meal-name-field"><span>種目名</span><input autoFocus required maxLength="60" placeholder="例：ベンチプレス" value={entry.exercise} onChange={(e) => setEntry({ ...entry, exercise: e.target.value })} /></label><div className="training-options"><label><input type="checkbox" checked={entry.sideMode} onChange={(e) => setSideMode(e.target.checked)} />左右別で記録する</label><label><input type="checkbox" checked={entry.assisted} onChange={(e) => setEntry({ ...entry, assisted: e.target.checked })} />補助あり</label></div>{entry.sideMode && <label className="same-side-toggle"><input type="checkbox" checked={entry.sidesSame} onChange={(e) => setSidesSame(e.target.checked)} />左右同じ</label>}{entry.sideMode && !entry.sidesSame ? <><EntryRows title="右" side="right" items={entriesFor('right')} assisted={entry.assisted} onUpdate={updateEntry} onAdd={addRow} onDelete={deleteRow} /><EntryRows title="左" side="left" items={entriesFor('left')} assisted={entry.assisted} onUpdate={updateEntry} onAdd={addRow} onDelete={deleteRow} /></> : <EntryRows title={entry.sideMode ? '左右共通' : null} side={commonSide} items={entriesFor(commonSide)} assisted={entry.assisted} onUpdate={updateEntry} onAdd={addRow} onDelete={deleteRow} />}<label className="field training-date-field"><span>記録日時</span><input required type="datetime-local" value={entry.recordedAt} onChange={(e) => setEntry({ ...entry, recordedAt: e.target.value })} /></label><label className="field training-memo-field"><span>トレーニングメモ <span className="field-description">任意</span></span><textarea maxLength="500" placeholder="体調、フォーム、気になったことなど" value={entry.memo} onChange={(e) => setEntry({ ...entry, memo: e.target.value })} /></label><p className="volume-preview">{entry.assisted ? '補助負荷量' : '総負荷量'} <strong>{volume.toLocaleString('ja-JP')} kg</strong><small>（合計 {totalSets}セット）</small></p><button className="button button-green meal-submit" type="submit"><Plus size={18} />記録を追加</button></form>;
}
